# .github/workflows/treebeard.yml
# Run all notebooks on every push and weekly
on:
  push:
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run treebeard
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: treebeardtech/treebeard@master